CREATE TABLE Doctor(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) NOT NULL,
    crm VARCHAR(15) NOT NULL,
    specializations VARCHAR(255) NOT NULL
);

CREATE TABLE Medicine(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	activeIngredient VARCHAR(255) NOT NULL,
    commercialName VARCHAR(255) NOT NULL,
    amount VARCHAR(255) NOT NULL
);

CREATE TABLE Patient(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    weight DECIMAL(5, 2) NOT NULL,
    height DECIMAL(5, 2) NOT NULL
);
